-- 1. Сначала создаем все таблицы БЕЗ внешних ключей
CREATE TABLE public.users (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    username varchar(50) NULL,
    hashed_password varchar(100) NULL,
    email varchar(100) NULL,
    first_name varchar(50) NULL,
    last_name varchar(50) NULL,
    is_active bool NULL,
    is_superuser bool NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.categories (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    name varchar(100) NULL,
    image_url varchar(255) NULL,
    thumbnail_url varchar(255) NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE public.products (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    name varchar(255) NULL,
    category_id int4 NULL,
    price float8 NULL,
    rating float8 NULL,
    description varchar NULL,
    main_image varchar(255) NULL,
    additional_images text NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE public.carts (
    id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int4 NULL,
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.orders (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int4 NULL,
    total float8 NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.orderdetails (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    order_id int4 NULL,
    product_id int4 NULL,
    quantity int4 NULL,
    CONSTRAINT orderdetails_pkey PRIMARY KEY (id)
);

CREATE TABLE public.reviews (
    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int4 NULL,
    product_id int4 NULL,
    text varchar(500) NULL,
    rating int4 NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cart_items (
    cart_id int4 NOT NULL,
    product_id int4 NOT NULL
);

CREATE TABLE public.alembic_version (
    version_num varchar(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- 2. Создаем индексы
CREATE UNIQUE INDEX ix_users_email ON public.users USING btree (email);
CREATE UNIQUE INDEX ix_users_username ON public.users USING btree (username);
CREATE UNIQUE INDEX ix_categories_name ON public.categories USING btree (name);
CREATE INDEX ix_products_name ON public.products USING btree (name);
CREATE INDEX ix_carts_id ON public.carts USING btree (id);

-- 3. Добавляем внешние ключи (после создания всех таблиц)
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id);
ALTER TABLE public.carts ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.orderdetails ADD CONSTRAINT orderdetails_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);
ALTER TABLE public.orderdetails ADD CONSTRAINT orderdetails_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id);
ALTER TABLE public.cart_items ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);

-- 4. Вставляем начальные данные
INSERT INTO public.categories ("name", image_url, thumbnail_url) VALUES
('Брюки', '/static/images/categories/6ddd09a2-14ce-4671-819b-bcb5f8f96150.JPG', '/static/images/categories/thumbnails/b147b4f4-f955-4464-83b9-239a5244c420.JPG'),
('Рубашки', '/static/images/categories/6e1d3dcb-080c-4412-a7aa-fb6993fafc44.jpg', '/static/images/categories/thumbnails/541d932c-f941-45c6-9996-e942a934906b.jpg'),
('Футболки', '/static/images/categories/cc59c4da-ecf3-4f00-90d8-c37c18c7098c.jpg', '/static/images/categories/thumbnails/1452d93d-51ec-4f3d-8a4a-9e54b589b660.jpg'),
('Шорты', '/static/images/categories/1f8e4480-4eeb-4eb8-a738-23139bcb09f2.jpg', '/static/images/categories/thumbnails/d9af0f97-c7c4-4559-ab9a-7b4b8355f8cd.jpg'),
('Джинсы', '/static/images/categories/7f43fcce-140c-43ba-a6af-ab7a605fed81.jpg', '/static/images/categories/thumbnails/f1e27d8c-e186-4b0d-80e4-8a8810a01e3a.jpg'),
('Куртки', '/static/images/categories/6a987d77-ff7e-435d-ab16-22724008e690.jpg', '/static/images/categories/thumbnails/5335936f-4d4d-4081-96b7-8e875a553929.jpg');

INSERT INTO public.products ("name", category_id, price, rating, description, main_image, additional_images) VALUES
('Брюки Каро', 1, 4999.0, 0.0, 'Стильные и практичные брюки карго...', '/static/images/products/main_3_b88e18a0-0f8f-47cf-878d-8fcff7e85a41.jpg', '["/static/images/products/additional_3_7e8c2246-90cf-4e5e-a994-9c739c633adc.jpg", "/static/images/products/additional_3_80e10cf8-6237-4af9-b75c-71a90f102cf4.jpg", "/static/images/products/additional_3_ce1daf3e-1179-44a1-aa94-10c5399e54cb.jpg", "/static/images/products/additional_3_881c0edd-2355-4ce7-8cba-fc9ecf3e3b94.jpg"]'),
('Брюки из микротвила', 1, 2999.0, 0.0, 'Брюки из микротвила...', '/static/images/products/main_4_112b489f-9e73-4077-b828-536d40c5527e.jpg', '["/static/images/products/additional_4_a26d63a8-7a1d-4e36-9f2e-4818152914bb.jpg", "/static/images/products/additional_4_fdcc9c57-cae0-4ed4-9030-a9b07f14f473.jpg", "/static/images/products/additional_4_7593677d-3faa-4c63-9242-0c0dcb4e4c83.jpg", "/static/images/products/additional_4_9bff1e74-ef9d-48d6-86a2-7452568096b7.jpg"]');

INSERT INTO public.users (username, hashed_password, email, first_name, last_name, is_active, is_superuser) VALUES
('admin', '$2b$12$qIH0kthyFB./VfImqh5/x.b.aA/cpkm8oYnQ0xB2YHA9HYHQmYhEy', 'admin@example.com', 'admin', 'admin', true, true),
('one', '$2b$12$/qrTtIDYWQVLqAoeuNZd0ObuIGKlXtDtrSX86WkAnu5YQbtSYCuy2', 'one@one.ru', 'Nest', 'One', true, false),
('two', '$2b$12$FQqW1c/SUoefk4dBKTQqoOS0xvyj2AB1fWzNJIYJ60xfUw31HiZHK', 'two@two.ru', 'Второй', 'Пользователь', true, false);

-- 5. Вставляем тестовые данные в другие таблицы (по желанию)
INSERT INTO public.carts (user_id) VALUES (2), (3);
INSERT INTO public.cart_items (cart_id, product_id) VALUES (1, 1), (1, 2);