"""Initial migration

Revision ID: 3a0d838a23d9
Revises: 
Create Date: 2025-05-02 00:12:02.969195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0d838a23d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_index('ix_roles_level', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    op.add_column('categories', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('main_image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('additional_images', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'additional_images')
    op.drop_column('products', 'main_image')
    op.drop_column('categories', 'thumbnail_url')
    op.drop_column('categories', 'image_url')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_level', 'roles', ['level'], unique=True)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
